services:
  pythonapp:
    build: ./python/
    command: ["./wait-for-it.sh", "mysql:3306", "--", "flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./python:/app
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'