services:
  pythonapp:
    build: ./python/
    command: ["./wait-for-it.sh", "mysql:3306", "--", "flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./python:/python
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    ports:
      - '5000:5000'
    networks:
      - custom_network
    depends_on:
      - mysql

  tests:
    build: ./python/
    command: ["/python/app/wait-for-it.sh", "mysql:3306", "--", "python", "-m", "unittest", "discover"]
    networks:
      - custom_network
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: Accounts
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom_network
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  custom_network: