services:
  pythonapp:
    build: ./python/
    command: ["./wait-for-it.sh", "mysql:3306", "--", "flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./python:/python
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    depends_on:
      - mysql
    ports:
      - '5000:5000'

  tests:
    build: ./python/
    command: ["/python/app/wait-for-it.sh", "mysql:3306", "--", "python", "-m", "unittest", "discover"]
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data: