---
name: Testing

on: [push]

jobs:
  py-backend-tests:
    name: Run Python Backend Tests
    runs-on: ubuntu-20.04
    steps:
    #remove these #'s after secrets is sorted
      #- name: Docker Login
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USER }}
      #    password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Python Backend Tests
        run: |
          cd app/backend/python
          docker-compose build
          docker-compose run tests